[constants]
; All units are pixels, seconds, pixels per second, etc.
;TextHeight = 13
ArenaWidth = 1280
ArenaHeight = 800
;PushHeight = 75
;PushSpeed = 15
;MaxActivePlatforms = 8
; up is positive, so Gravity shouldn't be.  Since dudes are 50 pixels high, this is roughly equivalent to standard 9.8ms^-2.(down)
;Gravity = -250.0
;DudeWidth = 20
;DudeHeight = 50
;PlatformPadding = 5.0
;TeabagTime = 0.8

[colours]
; Background should be something that works well with chroma key filtering.  Snot green works for me.
Background = g255
;Platform = b255
;PlatformText = r255b255g255
;NameText = r255b255g255
;HitpointsText = r255
		