//go:build exclude
package main

// Read the batman_words.txt file, output map of (word, times used) ordered by times used.
// Words used 1 or 2 times are skipped as they tend to look stupid - either because they are single-story gags 
// which don't work well without context, or because they actually are stupid - too stupid even for the zyxoverlay,
// which is really saying something.  (As an example, "FLRBBBBB" barely squeaks in with 3 uses)
//
// Usage: just "go run" this file in the directory where it resides.

import (
	"bufio"
	"fmt"
	"log"
	"os"
	"sort"
	"strings"
)

func main() {
	word_count := map[string]int{}

	// Read file into word_count
	file, err := os.Open("batman_words.txt")
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		text := scanner.Text()
		if strings.HasPrefix(text, "#") {
			// This line is a comment
			continue
		}

		for _, word := range strings.Split(text, " ")[1:] { // First string in each line is an episode number
			// I love Go
			word_count[word] = word_count[word] + 1
		}
	}

	// Copy to array
	type word_and_count struct {
		word  string
		count int
	}
	keep_list := []word_and_count{}
	for word, count := range word_count {
		if count > 2 {
			keep_list = append(keep_list, word_and_count{word, count})
		}
	}

	// Sort it ("less" function is reversed for descending order)
	sort.Slice(keep_list, func(l,r int)bool{return keep_list[l].count>keep_list[r].count})

	// Output ready-to-paste map
	fmt.Println("// Wholly Generated Map, Batman!")
	fmt.Println("// Generated by batman_generator.go")
	fmt.Println("var word_map = map[string]int{")
	for _, wac := range keep_list {
		fmt.Printf("   \"%v\": %v,\n", strings.ToUpper(wac.word), wac.count)
	}
	fmt.Println("}")
}
