package batman_words

import "math/rand"

// Wholly Generated Map, Batman!
// Generated by batman_generator.go
var word_map = map[string]int{
   "KAPOW": 43,
   "BOFF": 39,
   "SOCK": 37,
   "POW": 35,
   "ZAP": 33,
   "OOOOFF": 30,
   "WHAMM": 27,
   "SPLATT": 26,
   "CRASH": 26,
   "BIFF": 26,
   "BAM": 22,
   "ZOWIE": 21,
   "WHAP": 20,
   "WHACK": 19,
   "ZAMM": 17,
   "CRUNCH": 15,
   "EEE-YOW": 12,
   "Z-ZWAP": 10,
   "BONK": 10,
   "ZLOPP": 9,
   "VRONK": 9,
   "ZLONK": 8,
   "KLONK": 8,
   "THUNK": 8,
   "OUCH": 7,
   "KAYO": 7,
   "SWOOSH": 6,
   "CLUNK": 6,
   "PAM": 6,
   "UGGH": 5,
   "THWACK": 5,
   "RAKKK": 4,
   "ZOK": 4,
   "THWAPP": 4,
   "CLANK": 4,
   "POWIE": 4,
   "CLASH": 4,
   "URKKK": 4,
   "FLRBBBBB": 3,
   "BANG": 3,
   "TOUCHÉ": 3,
   "AWKKKKKK": 3,
   "ZZZZZWAP": 3,
   "CR-R-A-A-CK": 3,
   "CRRAACK": 3,
}


var word_lookup []string

func init(){
	for word, count:=range word_map{
		for range(count){
			// Strings are shallow-copied, so this isn't (quite) as fumb as it looks
			word_lookup=append(word_lookup, word)
		}
	}
}

// Get_word returns a random Batman Violence Onomatopoeia Word,
// weighted according to observed word frequency in the 60's TV show.
func Get_word()string{
	return word_lookup[rand.Intn(len(word_lookup))]
}